config/routes.rb
RailsProblem::Application.routes.draw do
  resources :bubble_gums

  root :to => 'bubble_gums#index'

end

app/models/bubble_gum.rb
class BubbleGum < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bubble_gums_controller.rb
class BubbleGumsController < ApplicationController
  # GET /bubble_gums
  # GET /bubble_gums.json
  def index
    @bubble_gums = BubbleGum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bubble_gums }
    end
  end

  # GET /bubble_gums/1
  # GET /bubble_gums/1.json
  def show
    @bubble_gum = BubbleGum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @bubble_gum }
    end
  end

  # GET /bubble_gums/new
  # GET /bubble_gums/new.json
  def new
    @bubble_gum = BubbleGum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @bubble_gum }
    end
  end

  # GET /bubble_gums/1/edit
  def edit
    @bubble_gum = BubbleGum.find(params[:id])
  end

  # POST /bubble_gums
  # POST /bubble_gums.json
  def create
    @bubble_gum = BubbleGum.new(params[:bubble_gum])

    respond_to do |format|
      if @bubble_gum.save
        format.html { redirect_to @bubble_gum, :notice => 'Bubble gum was successfully created.' }
        format.json { render :json => @bubble_gum, :status => :created, :location => @bubble_gum }
      else
        format.html { render :action => "new" }
        format.json { render :json => @bubble_gum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bubble_gums/1
  # PUT /bubble_gums/1.json
  def update
    @bubble_gum = BubbleGum.find(params[:id])

    respond_to do |format|
      if @bubble_gum.update_attributes(params[:bubble_gum])
        format.html { redirect_to @bubble_gum, :notice => 'Bubble gum was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @bubble_gum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bubble_gums/1
  # DELETE /bubble_gums/1.json
  def destroy
    @bubble_gum = BubbleGum.find(params[:id])
    @bubble_gum.destroy

    respond_to do |format|
      format.html { redirect_to bubble_gums_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bubble_gums_helper.rb
module BubbleGumsHelper
end

app/views/bubble_gums/_form.html.erb
<%= form_for(@bubble_gum) do |f| %>
  <% if @bubble_gum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bubble_gum.errors.count, "error") %> prohibited this bubble_gum from being saved:</h2>

      <ul>
      <% @bubble_gum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bubble_gums/edit.html.erb
<h1>Editing bubble_gum</h1>

<%= render 'form' %>

<%= link_to 'Show', @bubble_gum %> |
<%= link_to 'Back', bubble_gums_path %>

app/views/bubble_gums/index.html.erb
<h1>Listing bubble_gums</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bubble_gums.each do |bubble_gum| %>
  <tr>
    <td><%= bubble_gum.name %></td>
    <td><%= link_to 'Show', bubble_gum %></td>
    <td><%= link_to 'Edit', edit_bubble_gum_path(bubble_gum) %></td>
    <td><%= link_to 'Destroy', bubble_gum, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bubble gum', new_bubble_gum_path %>

app/views/bubble_gums/new.html.erb
<h1>New bubble_gum</h1>

<%= render 'form' %>

<%= link_to 'Back', bubble_gums_path %>

app/views/bubble_gums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bubble_gum.name %>
</p>


<%= link_to 'Edit', edit_bubble_gum_path(@bubble_gum) %> |
<%= link_to 'Back', bubble_gums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsProblem</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>